from .pick_cube import solve as solvePickCube
from .stack_cube import solve as solveStackCube
from .peg_insertion_side import solve as solvePegInsertionSide
from .place_sphere import solve as solvePlaceSphere
from .plug_charger import solve as solvePlugCharger
from .push_cube import solve as solvePushCube
from .pull_cube_tool import solve as solvePullCubeTool
from .lift_peg_upright import solve as solveLiftPegUpright
from .pull_cube import solve as solvePullCube
from .draw_svg import solve as solveDrawSVG
from .draw_triangle import solve as solveDrawTriangle
from .stack_pyramid import solve as solveStackPyramid
from .obstacle_tasks import solveDeepBox, solveShelf, solveBarrier
from .make_iced_coffee import solve as solveMakeIcedCoffee
from .open_door import solve as solveOpenDoor
from .hang_mug import solve as solveHangMug
from .turn_on_sink_faucet import solve as solveTurnOnSinkFaucet
from .pick_place_toaster_to_counter import solve as solvePickPlaceToasterToCounter
